sudo: required
services:
  - docker

before_install:
  - docker build -t sandeepshiv/docker-reac -f Dockerfile.dev .

script:
  - docker run sandeepshiv/docker-reac npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-reac"
  env: "Dockerreac-env"
  bucket_name: "elasticbeanstalk-us-east-2-173071480411"
  bucket_path: "docker-reac"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

